import { createRVC, runPipelineInWorker } from "https://cdn.jsdelivr.net/npm/rvc-web-runtime@1.0.5/+esm";
const $=id=>document.getElementById(id),status=$("status");
const DB_NAME="voicechanger",DB_VERSION=1,STORE="models";
const SUPPORT={contentVec:"https://huggingface.co/MoeSS-SUBModel/resolve/main/vec-768-layer-12.onnx",rmvpe:"https://huggingface.co/MoeSS-SUBModel/resolve/main/RMVPE.onnx"};
let rvc=null,files=null,audioCtx=null,mediaStream=null,worklet=null,running=false,queue=[],processing=false,playAt=0;
function say(t,k=""){status.textContent=t;status.className="status "+k}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbGet(k){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE,"readonly").objectStore(STORE).get(k);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function dbPut(k,v){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(v,k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getModel(){const chosen=$("model").files[0];if(chosen){const data=await chosen.arrayBuffer();const saved={name:chosen.name,type:chosen.type||"application/octet-stream",data};await dbPut("target",saved);return new File([data],saved.name,{type:saved.type})}const saved=await dbGet("target");if(!saved)return null;return new File([saved.data],saved.name,{type:saved.type})}
async function getSupport(name,url,label){const cached=await dbGet(name);if(cached){say("Using saved "+label+" model...");return new File([cached.data],cached.name,{type:"application/octet-stream"})}say("Downloading "+label+" model once...");const res=await fetch(url,{mode:"cors"});if(!res.ok)throw Error(label+" download failed ("+res.status+").");const data=await res.arrayBuffer();await dbPut(name,{name:label+".onnx",data});return new File([data],label+".onnx",{type:"application/octet-stream"})}
async function loadVoice(){try{$("load").disabled=true;if(!("gpu" in navigator))throw Error("WebGPU is not available in this Chrome build.");const adapter=await navigator.gpu.requestAdapter();if(!adapter)throw Error("No WebGPU adapter found. Turn on Chrome hardware acceleration.");const model=await getModel();if(!model)throw Error("Choose your RVC v2 .onnx voice model first.");const [contentVec,rmvpe]=await Promise.all([getSupport("contentVec",SUPPORT.contentVec,"ContentVec"),getSupport("rmvpe",SUPPORT.rmvpe,"RMVPE")]);files={model,contentVec,rmvpe};rvc=createRVC();say("Voice model built and saved in this browser. Press Start.","ok");$("start").disabled=false}catch(e){files=null;$("start").disabled=true;say("Load error: "+e.message,"err")}finally{$("load").disabled=false}}
function makeWorklet(){const code=`class MicChunker extends AudioWorkletProcessor{constructor(){super();this.buf=[];this.n=0;this.target=sampleRate*2.5}process(inputs){const ch=inputs[0]?.[0];if(!ch)return true;for(let i=0;i<ch.length;i++){this.buf.push(ch[i]);this.n++}while(this.n>=this.target){const out=new Float32Array(Math.floor(this.target));for(let i=0;i<out.length;i++)out[i]=this.buf[i];this.buf=this.buf.slice(out.length);this.n-=out.length;this.port.postMessage(out,[out.buffer])}return true}}registerProcessor("mic-chunker",MicChunker);`;return URL.createObjectURL(new Blob([code],{type:"application/javascript"}))}
async function start(){if(!files)return say("Build the voice model first.","err");try{$("start").disabled=true;$("stop").disabled=false;running=true;queue=[];processing=false;playAt=0;audioCtx=new AudioContext({latencyHint:"interactive"});await audioCtx.resume();mediaStream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:false,noiseSuppression:false,autoGainControl:false}});const src=audioCtx.createMediaStreamSource(mediaStream);const url=makeWorklet();await audioCtx.audioWorklet.addModule(url);URL.revokeObjectURL(url);worklet=new AudioWorkletNode(audioCtx,"mic-chunker");const mute=audioCtx.createGain();mute.gain.value=0;src.connect(worklet);worklet.connect(mute);mute.connect(audioCtx.destination);worklet.port.onmessage=e=>{if(!running)return;queue.push(e.data);if(queue.length>3)queue.shift();processQueue()};say("Mic is ON. Voice conversion is running continuously.","ok")}catch(e){stop();say("Start error: "+e.message,"err")}}
async function processQueue(){if(processing||!running||!queue.length)return;processing=true;const audio=queue.shift();try{say("Converting voice locally...");const result=await runPipelineInWorker(rvc,files,audio,audioCtx.sampleRate,{onEvent:e=>{if(e.type==="stage")say("RVC: "+e.stage)}},{contentVecBackend:"webgpu",rmvpeBackend:"webgpu",rvcBackend:"wasm",pitchShift:0,medianFilter:true,chunkDuration:2.5,padDuration:.35,inputSampleRate:16000,outputSampleRate:48000,timeout:120000});if(result.state!=="success"||!result.outputWav)throw Error(result.errorMessage||"RVC conversion failed.");await playWav(result.outputWav);say("Voice converted. Mic remains continuous.","ok")}catch(e){say("Conversion error: "+e.message,"err")}finally{processing=false;if(running)processQueue()}}
async function playWav(blob){const buf=await blob.arrayBuffer(),decoded=await audioCtx.decodeAudioData(buf.slice(0)),src=audioCtx.createBufferSource();src.buffer=decoded;src.connect(audioCtx.destination);const now=audioCtx.currentTime;if(playAt<now)playAt=now+.03;src.start(playAt);playAt+=decoded.duration}
function stop(){running=false;queue=[];try{worklet?.disconnect()}catch{}try{mediaStream?.getTracks().forEach(t=>t.stop())}catch{}worklet=null;mediaStream=null;processing=false;$("stop").disabled=true;$("start").disabled=!files;say(files?"Stopped. Saved voice model stays loaded.":"Choose a voice model first.")}
$("load").onclick=loadVoice;$("start").onclick=start;$("stop").onclick=stop;addEventListener("beforeunload",stop);
(async()=>{try{const saved=await dbGet("target");if(saved){$("load").textContent="Use saved voice model";say("Saved voice model found. Press the button to load it.")}}catch{}})();