const $ = id => document.getElementById(id);
const micSel=$('mic'), outSel=$('output');
const choose=$('choose'), startBtn=$('load'), stopBtn=$('stop');
const status=$('status'), meter=$('meter');
const TTS_URL='http://127.0.0.1:8100/v1/audio/speech';
const HEALTH_URL='http://127.0.0.1:8100/health';
let recognition=null,running=false,ctx=null,currentAudio=null,speaking=false,queue=[];
function setStatus(s){status.textContent=s;}
async function devices(){if(!navigator.mediaDevices?.enumerateDevices)return;try{const ds=await navigator.mediaDevices.enumerateDevices(),mi=micSel.value,ou=outSel.value;micSel.innerHTML='<option value="">Default microphone</option>';outSel.innerHTML='<option value="">Default output</option>';ds.filter(d=>d.kind==='audioinput').forEach((d,i)=>micSel.append(new Option(d.label||`Microphone ${i+1}`,d.deviceId)));ds.filter(d=>d.kind==='audiooutput').forEach((d,i)=>outSel.append(new Option(d.label||`Speaker ${i+1}`,d.deviceId)));if([...micSel.options].some(o=>o.value===mi))micSel.value=mi;if([...outSel.options].some(o=>o.value===ou))outSel.value=ou;}catch(e){console.warn(e);}}
async function ensureContext(){if(!ctx)ctx=new AudioContext({latencyHint:'interactive'});await ctx.resume();if(ctx.setSinkId&&outSel.value)try{await ctx.setSinkId(outSel.value);}catch(e){console.warn(e);}}
async function chooseOutput(){if(!navigator.mediaDevices?.selectAudioOutput){setStatus('Chrome does not expose speaker selection here. Use the system default output.');return;}try{const d=await navigator.mediaDevices.selectAudioOutput();if(d)outSel.value=d.deviceId;await ensureContext();}catch(e){if(e.name!=='NotAllowedError')setStatus('Speaker selection: '+e.message);}}
async function speak(text){const response=await fetch(TTS_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:'piper',input:text,voice:'en_US-amy-medium',response_format:'wav'})});if(!response.ok){let detail='HTTP '+response.status;try{const j=await response.json();detail=j.error||detail;}catch{}throw new Error(detail);}const bytes=await response.arrayBuffer();await ensureContext();const buffer=await ctx.decodeAudioData(bytes.slice(0));await new Promise((resolve,reject)=>{const src=ctx.createBufferSource();src.buffer=buffer;src.connect(ctx.destination);currentAudio=src;speaking=true;src.onended=()=>{speaking=false;currentAudio=null;resolve();processQueue();};src.onerror=reject;src.start();});}
async function processQueue(){if(speaking||!queue.length||!running)return;const text=queue.shift();try{setStatus('Amy: '+text);meter.style.width='85%';await speak(text);meter.style.width='100%';}catch(e){speaking=false;setStatus('Piper TTS error: '+(e?.message||e));}}
function startRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setStatus('This Chrome build does not provide SpeechRecognition.');return;}recognition=new SR();recognition.continuous=true;recognition.interimResults=true;recognition.lang='en-US';recognition.maxAlternatives=1;recognition.onstart=()=>setStatus('Listening… Amy is ready.');recognition.onerror=e=>{if(e.error!=='no-speech'&&e.error!=='aborted')setStatus('Speech recognition: '+e.error);};recognition.onend=()=>{if(running)try{recognition.start();}catch{}};recognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){const r=e.results[i];if(r.isFinal){const text=r[0].transcript.trim();if(text){queue.push(text);processQueue();}}}};try{recognition.start();}catch{}}
async function start(){if(running)return;try{const constraints={audio:{channelCount:1,echoCancellation:false,noiseSuppression:false,autoGainControl:false}};if(micSel.value)constraints.audio.deviceId={exact:micSel.value};const stream=await navigator.mediaDevices.getUserMedia(constraints);stream.getTracks().forEach(t=>t.stop());await devices();await ensureContext();const health=await fetch(HEALTH_URL,{cache:'no-store'});if(!health.ok)throw new Error('Local Piper bridge is not ready');running=true;queue=[];startRecognition();startBtn.textContent='RUNNING';startBtn.disabled=true;meter.style.width='15%';setStatus('Listening… Piper Amy is ready.');}catch(e){running=false;setStatus('Start error: '+(e?.message||e)+'. Run piper/start_piper.bat first.');}}
function stop(){running=false;queue=[];try{recognition?.stop();}catch{}recognition=null;try{currentAudio?.stop();}catch{}currentAudio=null;speaking=false;startBtn.disabled=false;startBtn.textContent='START';meter.style.width='0%';setStatus('Stopped.');}
startBtn.onclick=()=>void start();stopBtn.onclick=stop;choose.onclick=()=>void chooseOutput();outSel.onchange=()=>void ensureContext();navigator.mediaDevices?.addEventListener?.('devicechange',devices);void devices();