const $=id=>document.getElementById(id);
const bridgeEl=$("bridge"),micSel=$("mic"),outSel=$("output"),choose=$("choose"),voice=$("voice"),content=$("content"),rmvpe=$("rmvpe"),start=$("start"),stop=$("stop"),status=$("status"),meter=$("meter");
const BRIDGE="http://127.0.0.1:8765";
let running=false,ctx=null,stream=null,source=null,inputNode=null,outputNode=null,buf=[],processing=false;
function setStatus(x){status.textContent=x}
async function bridgeStatus(){try{const r=await fetch(BRIDGE+"/status",{cache:"no-store"});const j=await r.json();bridgeEl.innerHTML=j.ready?'<span class="ok">● Bridge ready</span>':'● Bridge running; model not loaded';if(j.error)bridgeEl.textContent+=" — "+j.error;return true}catch{bridgeEl.textContent="● Bridge not running";return false}}
async function devices(){if(!navigator.mediaDevices?.enumerateDevices)return;const ds=await navigator.mediaDevices.enumerateDevices(),mi=micSel.value,ou=outSel.value;micSel.innerHTML='<option value="">Default microphone</option>';outSel.innerHTML='<option value="">Default output</option>';ds.filter(d=>d.kind==='audioinput').forEach(d=>micSel.append(new Option(d.label||`Microphone ${micSel.length}`,d.deviceId)));ds.filter(d=>d.kind==='audiooutput').forEach(d=>outSel.append(new Option(d.label||`Speaker ${outSel.length}`,d.deviceId)));if([...micSel.options].some(o=>o.value===mi))micSel.value=mi;if([...outSel.options].some(o=>o.value===ou))outSel.value=ou}
async function chooseOutput(){if(navigator.mediaDevices?.selectAudioOutput){try{const d=await navigator.mediaDevices.selectAudioOutput();if(d)outSel.value=d.deviceId;await setSink()}catch(e){if(e.name!=='NotAllowedError')setStatus(e.message)}}}
async function setSink(){if(ctx?.setSinkId){try{await ctx.setSinkId(outSel.value||'')}catch(e){console.warn(e)}}}
function micCode(){return `class MicCapture extends AudioWorkletProcessor{process(i){const c=i[0]?.[0];if(c)this.port.postMessage(c.slice());return true}}registerProcessor('mic-capture',MicCapture);`}
function outCode(){return `class RvcOut extends AudioWorkletProcessor{constructor(){super();this.q=[];this.pos=0;this.port.onmessage=e=>{if(e.data instanceof Float32Array)this.q.push(e.data)}}process(i,o){const a=o[0][0];for(let n=0;n<a.length;n++){if(!this.q.length){a[n]=0;continue}const b=this.q[0];a[n]=b[this.pos++]||0;if(this.pos>=b.length){this.q.shift();this.pos=0}}return true}}registerProcessor('rvc-out',RvcOut);`}
async function loadModel(){const q=new URLSearchParams({voice:voice.value,content:content.value,pitch:rmvpe.value});const r=await fetch(BRIDGE+"/load?"+q);const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Native model load failed')}
async function sendBlock(block){while(processing)await new Promise(r=>setTimeout(r,0));processing=true;try{const body=block.buffer.slice(block.byteOffset,block.byteOffset+block.byteLength);const r=await fetch(BRIDGE+"/process",{method:'POST',headers:{'Content-Type':'application/octet-stream'},body});if(!r.ok)throw new Error('Native conversion request failed');const ab=await r.arrayBuffer(),out=new Float32Array(ab);outputNode?.port.postMessage(out,[out.buffer])}finally{processing=false}}
function takeBlock(){const b=new Float32Array(4800);for(let i=0;i<b.length;i++)b[i]=buf.shift()||0;return b}
async function startAll(){if(running)return;try{if(!await bridgeStatus())throw new Error('Start the local native bridge first.');await loadModel();const constraints={audio:{channelCount:1,echoCancellation:false,noiseSuppression:false,autoGainControl:false}};if(micSel.value)constraints.audio.deviceId={exact:micSel.value};stream=await navigator.mediaDevices.getUserMedia(constraints);await devices();ctx=new AudioContext({sampleRate:48000,latencyHint:'interactive'});await ctx.resume();await setSink();const a=new Blob([micCode()],{type:'application/javascript'}),b=new Blob([outCode()],{type:'application/javascript'});await ctx.audioWorklet.addModule(URL.createObjectURL(a));await ctx.audioWorklet.addModule(URL.createObjectURL(b));source=ctx.createMediaStreamSource(stream);inputNode=new AudioWorkletNode(ctx,'mic-capture');outputNode=new AudioWorkletNode(ctx,'rvc-out',{outputChannelCount:[1]});source.connect(inputNode);outputNode.connect(ctx.destination);buf=[];processing=false;running=true;start.disabled=true;stop.disabled=false;setStatus('Running — Chrome mic → existing DLL → Chrome output.');inputNode.port.onmessage=e=>{if(!running)return;const a=e.data;for(let i=0;i<a.length;i++)buf.push(a[i]);while(buf.length>=4800&&!processing)void sendBlock(takeBlock());meter.style.width=Math.min(100,buf.length/48)+'%'}}catch(e){console.error(e);await stopAll();setStatus('Start error: '+e.message)}}
async function stopAll(){running=false;start.disabled=false;stop.disabled=true;buf=[];try{inputNode?.disconnect();outputNode?.disconnect();source?.disconnect()}catch{}try{stream?.getTracks().forEach(t=>t.stop())}catch{}try{await ctx?.close()}catch{}ctx=null;inputNode=null;outputNode=null;source=null;setStatus('Stopped.')}
start.onclick=()=>void startAll();stop.onclick=()=>void stopAll();choose.onclick=()=>void chooseOutput();outSel.onchange=()=>void setSink();navigator.mediaDevices?.addEventListener?.('devicechange',devices);void devices();void bridgeStatus();setInterval(()=>{if(!running)void bridgeStatus()},2000);