services:
  - type: web
    name: voicechanger-openvoice
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: OPENVOICE_LANGUAGE
        value: EN_NEWEST
      - key: OPENVOICE_CONVERTER
        value: checkpoints_v2/converter
      - key: OPENVOICE_SOURCE_SE
        value: checkpoints_v2/base_speakers/ses/en-newest.pth
