import { VoxShot, ChatterboxEngine } from "https://esm.sh/voxshot@latest";
const $=id=>document.getElementById(id);let tts=null,recorder=null,chunks=[],referenceBlob=null,playing=null;
function status(s){$("status").textContent=s}function log(s){$("log").textContent=s}
async function load(){if(tts)return tts;$("startBtn").disabled=true;status("Loading VoxShot model...");
const engine=new ChatterboxEngine({onProgress:p=>{if(p.status==="progress")status(`Loading model... ${Math.round((p.progress||0)*100)}%`);else if(p.status==="load-start")status(`Trying ${p.plan||"WebGPU"}...`);else if(p.status==="load-fallback")status("WebGPU fallback: "+(p.reason||"trying next backend"));else if(p.status==="load-ready")status("Model ready: "+(p.plan||"local"))}});
tts=await VoxShot.create({engine,device:"auto",minChunkLength:20});$("startBtn").disabled=false;$("cloneBtn").disabled=!referenceBlob;log("VoxShot backend: "+(tts.device||"auto"));return tts}
$("startBtn").onclick=load;
$("recordBtn").onclick=async()=>{if(recorder?.state==="recording"){recorder.stop();$("recordBtn").textContent="🎙 Record 5–15 sec";return}const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{referenceBlob=new Blob(chunks,{type:recorder.mimeType||"audio/webm"});stream.getTracks().forEach(t=>t.stop());$("referenceInfo").textContent="Reference recorded.";$("cloneBtn").disabled=false};recorder.start();$("recordBtn").textContent="⏹ Stop recording";$("referenceInfo").textContent="Recording — speak naturally for 5–15 seconds."};
$("fileInput").onchange=()=>{const f=$("fileInput").files?.[0];if(f){referenceBlob=f;$("referenceInfo").textContent="Reference: "+f.name;$("cloneBtn").disabled=false}};
$("cloneBtn").onclick=async()=>{try{const v=await load();status("Cloning reference voice...");await v.cloneVoice(referenceBlob);status("Voice cloned!");$("speakBtn").disabled=false;log("Voice embedding cached locally.")}catch(e){console.error(e);status("Clone failed — open Chrome DevTools for details.");log(e?.message||String(e))}};
$("speakBtn").onclick=async()=>{const text=$("text").value.trim();if(!text||!tts)return;try{if(playing)await playing.stop();status("Speaking...");playing=tts.play(text,{speed:+$("speed").value,volume:1});await playing.done;status("Ready")}catch(e){console.error(e);status("Playback failed.");log(e?.message||String(e))}finally{playing=null}};
$("stopBtn").onclick=async()=>{if(playing)await playing.stop();playing=null;status(tts?"Ready":"Not loaded")};