<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>VoiceChangerMod</AssemblyName>
    <RootNamespace>VoiceChangerMod</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <IsPackable>false</IsPackable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Net.Http" />
    <PackageReference Include="LavaGang.MelonLoader" Version="0.7.3" PrivateAssets="all" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="UnityEngine.CoreModule" Version="2020.3.1" PrivateAssets="all" IncludeAssets="compile;build;analyzers;buildtransitive" />
    <PackageReference Include="UnityEngine.IMGUIModule" Version="2020.3.1" PrivateAssets="all" IncludeAssets="compile;build;analyzers;buildtransitive" />
  </ItemGroup>
</Project>
