import { pipeline, env } from 'https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.0.0';

const $=id=>document.getElementById(id);let tts=null,ref=null;
const status=s=>$("status").textContent=s;
async function devices(){try{const s=await navigator.mediaDevices.getUserMedia({audio:true});s.getTracks().forEach(t=>t.stop());const ds=await navigator.mediaDevices.enumerateDevices();const mi=$("mic"),ou=$("out");mi.innerHTML='';ou.innerHTML='';ds.filter(x=>x.kind==='audioinput').forEach((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||`Microphone ${i+1}`;mi.appendChild(o)});ds.filter(x=>x.kind==='audiooutput').forEach((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||`Output ${i+1}`;ou.appendChild(o)});status(`Found ${mi.options.length} microphone(s) and ${ou.options.length} output(s).`)}catch(e){status('Device error: '+e.message)}}
async function load(){try{status('Loading Chatterbox Turbo browser model… first load downloads model files and caches them.');env.allowLocalModels=false;env.useBrowserCache=true;tts=await pipeline('text-to-speech','onnx-community/chatterbox-ONNX',{dtype:'q4f16',device:'webgpu'});$("generate").disabled=false;status('Chatterbox Turbo loaded. Choose a WAV and generate speech.')}catch(e){status('Model load failed: '+e.message)}}
async function wavToFloat(file){const a=new AudioContext();const b=await a.decodeAudioData(await file.arrayBuffer());const x=b.getChannelData(0);const y=new Float32Array(x);await a.close();return y}
async function generate(){if(!tts)return;if(!ref)return status('Choose a reference WAV first.');try{status('Encoding reference voice…');const audio=await wavToFloat(ref);const out=await tts($("text").value,{speaker_audio:audio});const data=out.audio||out;const blob=new Blob([data.buffer||data],{type:'audio/wav'});const url=URL.createObjectURL(blob);const p=$("audio");p.src=url;const id=$("out").value;if(p.setSinkId)try{await p.setSinkId(id)}catch{}await p.play();status('Generated cloned speech.')}catch(e){status('Generation failed: '+e.message)}}
$("wav").onchange=e=>ref=e.target.files[0];$("load").onclick=load;$("generate").onclick=generate;$("refresh").onclick=devices;$("micTest").onclick=async()=>{try{const s=await navigator.mediaDevices.getUserMedia({audio:{deviceId:$("mic").value?{exact:$("mic").value}:undefined}});status('Microphone permission works.');s.getTracks().forEach(t=>t.stop())}catch(e){status('Microphone error: '+e.message)}};devices();
