const $=id=>document.getElementById(id);
let worker=null,referenceFile=null,loaded=false,encoded=false,request=0;
const status=s=>$("status").textContent=s;
function send(type,data={},transfer=[]){return new Promise((resolve,reject)=>{const id=++request;const on=e=>{const m=e.data;if(m.type==='progress'){const p=m.data;status(p?.status?`${p.status}: ${Math.round(p.progress||0)}%`:'Loading Chatterbox…');return}if(m.type==='error'){worker.removeEventListener('message',on);reject(new Error(m.data?.message||'Worker error'));return}if((type==='load'&&m.type==='loaded')||(type==='encode'&&m.type==='encoded')||(type==='generate'&&m.type==='generated')){worker.removeEventListener('message',on);resolve(m.data)}};worker.addEventListener('message',on);worker.postMessage({type,data},transfer)} )}
async function devices(){try{const s=await navigator.mediaDevices.getUserMedia({audio:true});s.getTracks().forEach(t=>t.stop());const ds=await navigator.mediaDevices.enumerateDevices();const mi=$("mic"),ou=$("out");mi.innerHTML='';ou.innerHTML='';ds.filter(x=>x.kind==='audioinput').forEach((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||`Microphone ${i+1}`;mi.appendChild(o)});ds.filter(x=>x.kind==='audiooutput').forEach((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||`Output ${i+1}`;ou.appendChild(o)});status(`Found ${mi.options.length} microphone(s) and ${ou.options.length} output(s).`)}catch(e){status('Device error: '+e.message)}}
async function decode24(file){const ac=new AudioContext();const b=await ac.decodeAudioData(await file.arrayBuffer());const src=b.getChannelData(0);const n=Math.round(src.length*24000/b.sampleRate);const out=new Float32Array(n);for(let i=0;i<n;i++){const pos=i*b.sampleRate/24000;const a=Math.floor(pos),f=pos-a;out[i]=(src[a]||0)*(1-f)+(src[a+1]||src[a]||0)*f}await ac.close();return out}
async function load(){try{$("load").disabled=true;status('Starting Chatterbox Turbo…');worker=new Worker('./tts.worker.js',{type:'module'});const r=await send('load',{device:navigator.gpu?'webgpu':'wasm'});loaded=true;status(`Chatterbox Turbo loaded on ${r.device}. Choose your WAV.`);$("generate").disabled=false}catch(e){status('Model load failed: '+e.message);$("load").disabled=false}}
async function encodeReference(){if(!loaded)return;referenceFile=$("wav").files[0];if(!referenceFile){status('Choose a reference WAV first.');return false}status('Encoding reference voice…');const audio=await decode24(referenceFile);await send('encode',{id:'main',audio:audio.buffer},[audio.buffer]);encoded=true;status('Voice clone ready.');return true}
function wavBlob(float32,sr){const buf=new ArrayBuffer(44+float32.length*2),v=new DataView(buf);const w=(o,s)=>{for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i))};w(0,'RIFF');v.setUint32(4,36+float32.length*2,true);w(8,'WAVE');w(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sr,true);v.setUint32(28,sr*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);w(36,'data');v.setUint32(40,float32.length*2,true);for(let i=0;i<float32.length;i++){const x=Math.max(-1,Math.min(1,float32[i]));v.setInt16(44+i*2,x<0?x*32768:x*32767,true)}return new Blob([buf],{type:'audio/wav'})}
async function generate(){try{if(!loaded)return;const ok=encoded||await encodeReference();if(!ok)return;const text=$("text").value.trim();if(!text)return status('Enter text first.');status('Generating cloned speech…');const r=await send('generate',{text,id:'main',exaggeration:0.5});const wav=new Float32Array(r.audio);const url=URL.createObjectURL(wavBlob(wav,r.sampleRate));const p=$("audio");p.src=url;if(p.setSinkId&&$("out").value){try{await p.setSinkId($("out").value)}catch{}}await p.play();status('Generated cloned speech.')}catch(e){status('Generation failed: '+e.message)}}
$("wav").onchange=()=>{encoded=false;if($("wav").files[0])status('Reference WAV selected. Click Generate cloned voice.')};$("load").onclick=load;$("generate").onclick=generate;$("refresh").onclick=devices;$("micTest").onclick=async()=>{try{const s=await navigator.mediaDevices.getUserMedia({audio:{deviceId:$("mic").value?{exact:$("mic").value}:undefined}});status('Microphone permission works.');s.getTracks().forEach(t=>t.stop())}catch(e){status('Microphone error: '+e.message)}};navigator.mediaDevices?.addEventListener?.('devicechange',devices);devices();
