import { AgentSession } from "https://esm.sh/@deepgram/agents@0.1.0";

const $=id=>document.getElementById(id);
let session=null,running=false,ctx=null,source=null,processor=null,stream=null,outputCtx=null,nextPlay=0,active=[];
const PROMPT=`Repeat exactly what the user says. Do not answer, interpret, summarize, correct, expand, paraphrase, translate, or add anything. Your response must contain only the user's latest utterance, verbatim as closely as possible. Never invent words.`;
function status(x){$("status").textContent=x} function conn(x){$("connection").textContent=x} function mode(x){$("mode").textContent=x}
function f16(a){const o=new Int16Array(a.length);for(let i=0;i<a.length;i++){const x=Math.max(-1,Math.min(1,a[i]));o[i]=x<0?x*32768:x*32767}return o}
function down(a,from,to){if(from===to)return a;const r=from/to,n=Math.floor(a.length/r),o=new Float32Array(n);for(let j=0;j<n;j++){const st=Math.floor(j*r),en=Math.min(a.length,Math.floor((j+1)*r));let s=0,c=0;for(let i=st;i<en;i++){s+=a[i];c++}o[j]=c?s/c:0}return o}
function stopPlayback(){for(const n of active){try{n.stop()}catch{}}active=[];nextPlay=outputCtx?.currentTime||0}
function play(chunk){if(!outputCtx)return;const a=chunk instanceof ArrayBuffer?new Int16Array(chunk):new Int16Array(chunk.buffer,chunk.byteOffset,chunk.byteLength/2);const b=outputCtx.createBuffer(1,a.length,24000),f=new Float32Array(a.length);for(let i=0;i<a.length;i++)f[i]=a[i]/32768;b.copyToChannel(f,0);const n=outputCtx.createBufferSource();n.buffer=b;n.connect(outputCtx.destination);nextPlay=Math.max(nextPlay,outputCtx.currentTime+.003);n.start(nextPlay);nextPlay+=b.duration;active.push(n);n.onended=()=>{active=active.filter(x=>x!==n)}}
async function refreshDevices(){try{const p=await navigator.mediaDevices.getUserMedia({audio:true});p.getTracks().forEach(t=>t.stop());const ds=await navigator.mediaDevices.enumerateDevices(),ins=ds.filter(d=>d.kind==='audioinput'),outs=ds.filter(d=>d.kind==='audiooutput');const i=$("input"),o=$("output");i.innerHTML='';o.innerHTML='';ins.forEach((d,n)=>{const x=document.createElement('option');x.value=d.deviceId;x.textContent=d.label||`Microphone ${n+1}`;i.appendChild(x)});outs.forEach((d,n)=>{const x=document.createElement('option');x.value=d.deviceId;x.textContent=d.label||`Output ${n+1}`;o.appendChild(x)});const ci=outs.find(d=>/cable input/i.test(d.label)),co=ins.find(d=>/cable output/i.test(d.label));$("deviceStatus").textContent=`${ins.length} input(s), ${outs.length} output(s). ${ci&&co?'VB-CABLE detected.':'VB-CABLE not detected.'}`;if(ci)o.value=ci.deviceId;if(co)i.value=co.deviceId}catch(e){status('Device error: '+e.message)}}
async function setOutput(){const id=$("output").value;if(!outputCtx)outputCtx=new AudioContext({sampleRate:24000,latencyHint:'interactive'});await outputCtx.resume();if(id&&outputCtx.setSinkId)try{await outputCtx.setSinkId(id)}catch(e){console.warn(e)}}
async function startAudio(){const id=$("input").value;stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:id?{exact:id}:undefined,channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:false}});ctx=new AudioContext({latencyHint:'interactive'});await ctx.resume();const rate=ctx.sampleRate;source=ctx.createMediaStreamSource(stream);processor=ctx.createScriptProcessor(2048,1,1);source.connect(processor);processor.connect(ctx.destination);processor.onaudioprocess=e=>{if(!running||!session)return;const a=e.inputBuffer.getChannelData(0),d=down(a,rate,16000);try{session.sendAudio(f16(d).buffer)}catch(err){console.warn(err)}let rms=0;for(const v of a)rms+=v*v;$("meter").style.width=Math.min(100,Math.sqrt(rms/a.length)*650)+'%'}}
function stopAudio(){try{processor?.disconnect()}catch{}try{source?.disconnect()}catch{}try{ctx?.close()}catch{}stream?.getTracks().forEach(t=>t.stop());processor=source=ctx=stream=null;$("meter").style.width='0%'}
function wire(){session.on('connecting',()=>conn('Connecting'));session.on('connected',()=>conn('Connected'));session.on('reconnecting',()=>conn('Reconnecting'));session.on('disconnected',r=>{conn('Disconnected');if(running)status('Disconnected: '+r)});session.on('welcome',()=>status('Deepgram welcomed the session.'));session.on('settings-applied',()=>{mode('Listening');status('Repeat-me agent ready. Speak normally.')});session.on('user-started-speaking',()=>{stopPlayback();mode('Listening')});session.on('agent-thinking',()=>mode('Thinking'));session.on('agent-started-speaking',()=>mode('Speaking'));session.on('agent-audio-done',()=>mode('Listening'));session.on('conversation-text',m=>{$("transcript").textContent+=`${m.role}: ${m.content}\n`});session.on('audio',chunk=>play(chunk));session.on('error',e=>status('Deepgram error: '+(e?.description||e?.message||JSON.stringify(e))));session.on('warning',e=>status('Deepgram warning: '+(e?.description||e?.message||JSON.stringify(e))));}
async function start(){if(running)return;const token=$("token").value.trim();if(!token)return status('Paste a fresh temporary Deepgram token first.');try{await setOutput();await refreshDevices();$("transcript").textContent='';session=new AgentSession({auth:{tokenFactory:async()=>token},audio:{input:{encoding:'linear16',sampleRate:16000},output:{encoding:'linear16',sampleRate:24000}},agent:{language:'en',listen:{provider:{type:'deepgram',version:'v2',model:'flux-general-en',eager_eot_threshold:0.4,eot_threshold:0.7,eot_timeout_ms:3500}},think:{provider:{type:'open_ai',model:'gpt-5-mini',temperature:0,prompt:PROMPT}},speak:{provider:{type:'deepgram',version:'v2',model:$("voice").value,speed:1.05}}},reconnect:{enabled:false}});wire();running=true;$("start").disabled=true;$("stop").disabled=false;await session.connect();await startAudio()}catch(e){status('START FAILED: '+(e?.stack||e?.message||e));running=false;$("start").disabled=false;$("stop").disabled=true;stopAudio();try{session?.disconnect()}catch{}session=null}}
function stop(){running=false;stopAudio();stopPlayback();try{session?.disconnect()}catch{}session=null;$("start").disabled=false;$("stop").disabled=true;conn('Disconnected');mode('Idle');status('Stopped.')}
$("start").onclick=start;$("stop").onclick=stop;$("refresh").onclick=refreshDevices;$("output").onchange=setOutput;$("cableIn").onclick=async()=>{await refreshDevices();const x=[...$("output").options].find(o=>/cable input/i.test(o.textContent));if(x){$("output").value=x.value;await setOutput();status('CABLE Input selected for TTS.')}};$("cableOut").onclick=async()=>{await refreshDevices();const x=[...$("input").options].find(o=>/cable output/i.test(o.textContent));if(x){$("input").value=x.value;status('CABLE Output selected as microphone.')}};navigator.mediaDevices?.addEventListener?.('devicechange',refreshDevices);refreshDevices();