const $=id=>document.getElementById(id);
let ws=null,ctx=null,source=null,processor=null,stream=null,running=false,settingsApplied=false;
let outputCtx=null,nextPlayTime=0,activeSources=new Set(),inputRate=48000,sendRate=24000;
const REPEAT_PROMPT=`Your only job is to repeat exactly what the user just said. Do not answer the user. Do not interpret, summarize, correct, expand, paraphrase, translate, or add anything. Repeat the latest user utterance verbatim as closely as possible. Never invent words. Never mention that you are repeating. Keep every response to exactly the user's latest utterance and nothing else.`;

function status(s){$("status").textContent=s}
function setConnection(s){$("connection").textContent=s}
function setMode(s){$("mode").textContent=s}
function stopPlayback(){for(const n of activeSources){try{n.stop()}catch{}}activeSources.clear();nextPlayTime=outputCtx?.currentTime||0}
function floatTo16(a){const out=new Int16Array(a.length);for(let i=0;i<a.length;i++){const x=Math.max(-1,Math.min(1,a[i]));out[i]=x<0?x*32768:x*32767}return out}
function downsample(buf,from,to){if(from===to)return buf;const ratio=from/to,outLen=Math.floor(buf.length/ratio),out=new Float32Array(outLen);let o=0,i=0;while(o<outLen){const end=Math.min(buf.length,Math.floor((o+1)*ratio));let sum=0,n=0;for(;i<end;i++){sum+=buf[i];n++}out[o++]=n?sum/n:0}return out}
function pcmToFloat(data){const dv=new DataView(data);const out=new Float32Array(data.byteLength/2);for(let i=0;i<out.length;i++)out[i]=dv.getInt16(i*2,true)/32768;return out}
async function setOutput(){const id=$("output").value;if(!outputCtx)return;try{if(outputCtx.setSinkId)await outputCtx.setSinkId(id||"default")}catch(e){console.warn(e)}}
async function ensureOutput(){if(!outputCtx)outputCtx=new AudioContext({sampleRate:24000,latencyHint:"interactive"});await outputCtx.resume();await setOutput()}
function playPcm(arrayBuffer){if(!outputCtx)return;const f=pcmToFloat(arrayBuffer);const b=outputCtx.createBuffer(1,f.length,24000);b.copyToChannel(f,0);const n=outputCtx.createBufferSource();n.buffer=b;n.connect(outputCtx.destination);const now=outputCtx.currentTime;nextPlayTime=Math.max(nextPlayTime,now+0.005);n.start(nextPlayTime);nextPlayTime+=b.duration;activeSources.add(n);n.onended=()=>activeSources.delete(n)}
async function refreshDevices(){try{const p=await navigator.mediaDevices.getUserMedia({audio:true});p.getTracks().forEach(t=>t.stop());const ds=await navigator.mediaDevices.enumerateDevices();const ins=ds.filter(d=>d.kind==='audioinput'),outs=ds.filter(d=>d.kind==='audiooutput');const i=$("input"),o=$("output");i.innerHTML='';o.innerHTML='';ins.forEach((d,n)=>{const x=document.createElement('option');x.value=d.deviceId;x.textContent=d.label||`Microphone ${n+1}`;i.appendChild(x)});outs.forEach((d,n)=>{const x=document.createElement('option');x.value=d.deviceId;x.textContent=d.label||`Output ${n+1}`;o.appendChild(x)});const ci=outs.find(d=>/cable input/i.test(d.label));const co=ins.find(d=>/cable output/i.test(d.label));$("deviceStatus").textContent=`${ins.length} input(s), ${outs.length} output(s). ${ci&&co?'VB-CABLE detected.':'VB-CABLE not detected.'}`;if(ci)o.value=ci.deviceId;if(co)i.value=co.deviceId}catch(e){status('Device error: '+e.message)}}
async function startAudio(){const id=$("input").value;stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:id?{exact:id}:undefined,channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:false}});ctx=new AudioContext({latencyHint:'interactive'});await ctx.resume();inputRate=ctx.sampleRate;source=ctx.createMediaStreamSource(stream);processor=ctx.createScriptProcessor(2048,1,1);source.connect(processor);processor.connect(ctx.destination);processor.onaudioprocess=e=>{if(!running||!settingsApplied||!ws||ws.readyState!==WebSocket.OPEN)return;const a=e.inputBuffer.getChannelData(0);const d=downsample(a,inputRate,sendRate);ws.send(floatTo16(d).buffer);let rms=0;for(const v of a)rms+=v*v;$("meter").style.width=Math.min(100,Math.sqrt(rms/a.length)*650)+'%'}}
function stopAudio(){try{processor?.disconnect()}catch{}try{source?.disconnect()}catch{}try{ctx?.close()}catch{}stream?.getTracks().forEach(t=>t.stop());processor=source=ctx=stream=null;$("meter").style.width='0%'}
function connect(){const token=$("token").value.trim();if(!token)throw Error('Paste a temporary Deepgram token first.');const protocols=['token',token];ws=new WebSocket('wss://agent.deepgram.com/v1/agent/converse',protocols);ws.binaryType='arraybuffer';ws.onopen=()=>{setConnection('Connected');status('Sending agent settings…');ws.send(JSON.stringify({type:'Settings',audio:{input:{encoding:'linear16',sample_rate:sendRate},output:{encoding:'linear16',sample_rate:24000,container:'none'}},agent:{language:'en',listen:{provider:{type:'deepgram',model:'flux-general-en',version:'v2',eot_threshold:0.65,eager_eot_threshold:0.45,eot_timeout_ms:1800}},think:{provider:{type:'open_ai',model:'gpt-5-mini',temperature:0,prompt:REPEAT_PROMPT}},speak:{provider:{type:'deepgram',version:'v2',model:$("voice").value,speed:1.05,expressivity:0}}}}))};ws.onmessage=e=>{if(typeof e.data==='string'){let m;try{m=JSON.parse(e.data)}catch{return}handle(m)}else playPcm(e.data)};ws.onerror=()=>status('Deepgram WebSocket error. Check the temporary token and browser permissions.');ws.onclose=()=>{setConnection('Disconnected');settingsApplied=false;if(running)status('Agent disconnected.');};}
function handle(m){switch(m.type){case'Welcome':status('Deepgram connected.');break;case'SettingsApplied':settingsApplied=true;setMode('Listening');status('Repeat-me agent ready. Speak normally.');break;case'UserStartedSpeaking':stopPlayback();setMode('Listening');break;case'AgentThinking':setMode('Thinking');break;case'AgentStartedSpeaking':setMode('Speaking');break;case'AgentAudioDone':setMode('Listening');break;case'ConversationText':{const role=m.role||m.message?.role||'unknown',text=m.content||m.message?.content||'';if(text)$("transcript").textContent+=`${role}: ${text}\n`;break}case'Error':status('Deepgram error: '+(m.description||m.message||JSON.stringify(m)));break;case'Warning':status('Deepgram warning: '+(m.description||m.message||JSON.stringify(m)));break}}
async function start(){if(running)return;try{await ensureOutput();await refreshDevices();running=true;$("start").disabled=true;$("stop").disabled=false;$("transcript").textContent='';connect();await startAudio()}catch(e){running=false;$("start").disabled=false;$("stop").disabled=true;status('START FAILED: '+(e.message||e));stopAudio()}}
function stop(){running=false;settingsApplied=false;stopAudio();stopPlayback();try{ws?.close()}catch{}ws=null;$("start").disabled=false;$("stop").disabled=true;setConnection('Disconnected');setMode('Idle');status('Stopped.')}
$("start").onclick=start;$("stop").onclick=stop;$("refresh").onclick=refreshDevices;$("output").onchange=setOutput;$("cableIn").onclick=async()=>{await refreshDevices();const o=$("output");const x=[...o.options].find(x=>/cable input/i.test(x.textContent));if(x){o.value=x.value;await setOutput();status('CABLE Input selected for TTS.')}};$("cableOut").onclick=async()=>{await refreshDevices();const i=$("input");const x=[...i.options].find(x=>/cable output/i.test(x.textContent));if(x){i.value=x.value;status('CABLE Output selected as microphone.')}};navigator.mediaDevices?.addEventListener?.('devicechange',refreshDevices);refreshDevices();
