const $=id=>document.getElementById(id);
let session=null,mic=null,player=null,running=false,outputId='default';
const PROMPT=`Repeat exactly what the user says. Do not answer, interpret, summarize, correct, paraphrase, translate, expand, or invent anything. Your response must contain only the user's latest utterance, verbatim as closely as possible.`;
const SDK='https://esm.sh/@deepgram/agents@latest';
let AgentSession,AgentMicrophone,AgentPlayer;
function status(x){$("status").textContent=x}
async function load(){try{({AgentSession,AgentMicrophone,AgentPlayer}=await import(SDK));status('Deepgram SDK loaded. Refresh devices, then START.')}catch(e){status('SDK load failed: '+e.message)}}
async function refresh(){try{const p=await navigator.mediaDevices.getUserMedia({audio:true});p.getTracks().forEach(t=>t.stop());const ds=await navigator.mediaDevices.enumerateDevices();const ins=ds.filter(d=>d.kind==='audioinput'),outs=ds.filter(d=>d.kind==='audiooutput');$('input').innerHTML='';$('output').innerHTML='';ins.forEach((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||`Microphone ${i+1}`;$('input').appendChild(o)});outs.forEach((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||`Output ${i+1}`;$('output').appendChild(o)});const ci=outs.find(d=>/cable input/i.test(d.label));const co=ins.find(d=>/cable output/i.test(d.label));if(ci){$('output').value=ci.deviceId}if(co){$('input').value=co.deviceId}status(`${ins.length} input(s), ${outs.length} output(s). ${ci&&co?'VB-CABLE detected.':''}`)}catch(e){status('Device error: '+e.message)}}
async function start(){if(running)return;try{if(!AgentSession)await load();const token=$('token').value.trim();if(!token)throw Error('Paste a temporary Deepgram token first.');await refresh();running=true;$('start').disabled=true;$('stop').disabled=false;status('Connecting…');player=new AgentPlayer({sampleRate:24000});const output=$('output').value;try{if(player.audioContext?.setSinkId)await player.audioContext.setSinkId(output||'default')}catch(e){console.warn('sink',e)}session=new AgentSession({auth:{tokenFactory:async()=>token},audio:{input:{encoding:'linear16',sampleRate:16000},output:{encoding:'linear16',sampleRate:24000}},reconnect:{enabled:true,maxAttempts:8,baseDelay:500,maxDelay:10000,jitter:true},keepAliveInterval:10000,agent:{language:'en',listen:{provider:{type:'deepgram',model:'flux-general-en',version:'v2'}},think:{provider:{type:'open_ai',model:'gpt-5-mini',temperature:0,prompt:PROMPT}},speak:{provider:{type:'deepgram',version:'v2',model:$('voice').value}}}});
session.on('connecting',()=>status('Connecting to Deepgram…'));session.on('connected',()=>status('Connected. Waiting for agent settings…'));session.on('welcome',()=>status('Deepgram welcomed the session.'));session.on('settings-applied',()=>status('🟢 Agent ready — speak.'));session.on('reconnecting',(n,d)=>status(`Reconnecting (${n}) in ${d} ms…`));session.on('disconnected',r=>status('Disconnected: '+r));session.on('sdk-error',e=>status('SDK error: '+e.message));session.on('error',m=>status('Deepgram error: '+JSON.stringify(m)));session.on('warning',m=>console.warn('Deepgram warning',m));session.on('audio',chunk=>player.queue(chunk));session.on('user-started-speaking',()=>player.interrupt());session.on('conversation-text',m=>{$('conversation').textContent+=`${m.role}: ${m.content}\n`});await session.connect();mic=new AgentMicrophone(data=>session.sendAudio(data),{sampleRate:16000,echoCancellation:true,noiseSuppression:true,autoGainControl:true});mic.on?.('error',e=>status('Microphone error: '+e.message));await mic.start();status('🟢 Listening — say something.')}catch(e){status('START FAILED:\n'+(e.stack||e.message||e));stop()}}
function stop(){running=false;try{mic?.stop()}catch{}try{session?.disconnect()}catch{}try{player?.dispose()}catch{}mic=null;session=null;player=null;$('start').disabled=false;$('stop').disabled=true;status('Stopped.')}
$('start').onclick=start;$('stop').onclick=stop;$('refresh').onclick=refresh;$('output').onchange=async()=>{try{if(player?.audioContext?.setSinkId)await player.audioContext.setSinkId($('output').value)}catch(e){status('Output selection failed: '+e.message)}};$('cableIn').onclick=async()=>{await refresh();const x=[...$('output').options].find(o=>/cable input/i.test(o.textContent));if(x){$('output').value=x.value;$('output').dispatchEvent(new Event('change'));status('CABLE Input selected.')}};$('cableOut').onclick=async()=>{await refresh();const x=[...$('input').options].find(o=>/cable output/i.test(o.textContent));if(x){$('input').value=x.value;status('CABLE Output selected.')}};load();refresh();