const { app, BrowserWindow, session, ipcMain } = require('electron');
const http = require('http');
const https = require('https');
const fs = require('fs');
const path = require('path');
const os = require('os');
const { spawn } = require('child_process');

app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required');
app.commandLine.appendSwitch('enable-features', 'AudioServiceOutOfProcess');
const mime = { '.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon' };
let server;
let rvcProcess = null;
const RVC_MODEL_URL = 'https://huggingface.co/audio-cpp/audio.cpp-gguf/resolve/main/RVC-GGUF/rvc-f16.gguf';
function webRoot(){return app.isPackaged?path.join(process.resourcesPath,'web'):path.join(__dirname,'..','web','dist');}
function rvcRoot(){return path.join(app.getPath('userData'),'rvc-pocket');}
function rvcCli(){const p=app.isPackaged?path.join(process.resourcesPath,'rvc-engine','audiocpp_cli.exe'):path.join(__dirname,'rvc-engine','audiocpp_cli.exe');return fs.existsSync(p)?p:'';}
function rvcModel(){return path.join(rvcRoot(),'rvc-f16.gguf');}
function downloadFile(url,destination){return new Promise((resolve,reject)=>{fs.mkdirSync(path.dirname(destination),{recursive:true});const get=(target)=>https.get(target,{headers:{'User-Agent':'VoiceChanger-RVC-Pocket'}},res=>{if([301,302,307,308].includes(res.statusCode)&&res.headers.location){res.resume();return get(res.headers.location);}if(res.statusCode!==200){res.resume();return reject(new Error(`RVC model download failed: HTTP ${res.statusCode}`));}const tmp=`${destination}.download`;const out=fs.createWriteStream(tmp);res.pipe(out);out.on('finish',()=>out.close(()=>{try{fs.renameSync(tmp,destination);resolve(destination);}catch(e){reject(e);}}));out.on('error',e=>{try{fs.unlinkSync(tmp);}catch{}reject(e);});}).on('error',reject);get(url);});}
async function ensureRvcModel(){fs.mkdirSync(rvcRoot(),{recursive:true});const p=rvcModel();if(!fs.existsSync(p)||fs.statSync(p).size<10000000)await downloadFile(RVC_MODEL_URL,p);return{path:p,size:fs.statSync(p).size};}
function convertRvcWav(base64Wav,options={}){if(process.platform!=='win32')throw new Error('RVC Pocket currently targets Windows desktop.');const cli=rvcCli();if(!cli)throw new Error('RVC Pocket engine is missing from this build.');if(typeof base64Wav!=='string'||base64Wav.length>30000000)throw new Error('Invalid or oversized WAV payload.');return ensureRvcModel().then(({path:model})=>new Promise((resolve,reject)=>{const stamp=`${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`;const input=path.join(os.tmpdir(),`rvc-pocket-${stamp}-in.wav`),output=path.join(os.tmpdir(),`rvc-pocket-${stamp}-out.wav`);fs.writeFileSync(input,Buffer.from(base64Wav,'base64'));const voiceId=String(options.voiceId||'default').replace(/[^a-z0-9_-]/gi,'')||'default';const blend=Math.max(0,Math.min(1,Number(options.retrievalBlend??0)));const args=['--backend','cpu','--task','vc','--family','rvc','--model',model,'--audio',input,'--out',output,'--request-option',`voice_id=${voiceId}`];if(blend>0)args.push('--request-option',`retrieval_blend=${blend}`);rvcProcess=spawn(cli,args,{windowsHide:true,stdio:['ignore','pipe','pipe']});let stderr='';rvcProcess.stderr.on('data',d=>stderr+=d.toString());const cleanup=()=>{for(const f of[input,output]){try{fs.unlinkSync(f);}catch{}}};rvcProcess.on('error',e=>{rvcProcess=null;cleanup();reject(e);});rvcProcess.on('exit',code=>{rvcProcess=null;if(code!==0||!fs.existsSync(output)){cleanup();return reject(new Error(stderr.trim()||`RVC exited with code ${code}`));}try{const result=fs.readFileSync(output).toString('base64');cleanup();resolve(result);}catch(e){cleanup();reject(e);}});}));}
function startLocalServer(){return new Promise((resolve,reject)=>{const root=path.resolve(webRoot()),index=path.join(root,'index.html');if(!fs.existsSync(index))return reject(new Error(`VoiceChanger UI missing: ${index}`));server=http.createServer((req,res)=>{try{let requestPath=decodeURIComponent((req.url||'/').split('?')[0]);if(requestPath==='/')requestPath='/index.html';const relative=path.normalize(requestPath).replace(/^([.][.][/\\])+/,''),filePath=path.resolve(root,`.${path.sep}${relative}`);if(filePath!==root&&!filePath.startsWith(root+path.sep)){res.writeHead(403);return res.end('Forbidden');}fs.readFile(filePath,(err,data)=>{if(err){res.writeHead(err.code==='ENOENT'?404:500);return res.end(err.code==='ENOENT'?'Not found':'Server error');}res.writeHead(200,{'Content-Type':mime[path.extname(filePath).toLowerCase()]||'application/octet-stream','Cache-Control':'no-store'});res.end(data);});}catch{res.writeHead(400);res.end('Bad request');}});server.on('error',reject);server.listen(0,'127.0.0.1',()=>resolve(`http://127.0.0.1:${server.address().port}/`));});}
async function createWindow(){const url=await startLocalServer();const win=new BrowserWindow({width:1180,height:900,minWidth:900,minHeight:680,backgroundColor:'#090b12',title:'VoiceChanger Direct',webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true,webSecurity:true,preload:path.join(__dirname,'preload.cjs')}});win.webContents.setAudioMuted(false);win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('before-input-event',(_event,input)=>{if(input.key==='F12'&&input.type==='keyDown')win.webContents.toggleDevTools();});win.webContents.on('console-message',(_event,_level,message)=>console.log(`[VoiceChanger Direct] ${message}`));await win.loadURL(url);}
ipcMain.handle('rvc:status',()=>({engine:!!rvcCli(),model:fs.existsSync(rvcModel()),modelPath:rvcModel()}));
ipcMain.handle('rvc:ensure-model',()=>ensureRvcModel());
ipcMain.handle('rvc:convert-wav',(_event,payload)=>convertRvcWav(payload?.base64Wav,payload?.options||{}));
app.whenReady().then(async()=>{session.defaultSession.setPermissionRequestHandler((_wc,permission,callback)=>callback(['media','microphone','speaker-selection','notifications'].includes(permission)));try{await createWindow();}catch(error){console.error('[VoiceChanger Direct] startup failed:',error);}app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow().catch(console.error);});});
app.on('before-quit',()=>{try{rvcProcess?.kill();}catch{}try{server?.close();}catch{}});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit();});process.on('uncaughtException',error=>console.error('[VoiceChanger Direct] uncaught:',error));process.on('unhandledRejection',error=>console.error('[VoiceChanger Direct] rejection:',error));
