import { VoxShot, ChatterboxEngine } from "https://esm.sh/voxshot@0.8.0";

const $=id=>document.getElementById(id);let tts=null,running=false,voiceReady=false,recognition=null,micStream=null,analyser=null,ctx=null,raf=0,lastText="",lastAt=0,ignoreUntil=0,busy=false;
const status=t=>$("status").textContent=t;
async function devices(){try{await navigator.mediaDevices.getUserMedia({audio:true}).then(s=>s.getTracks().forEach(t=>t.stop()));const ds=await navigator.mediaDevices.enumerateDevices();const mi=$("mic"),ou=$("out");mi.innerHTML="<option value=''>Default microphone</option>";ou.innerHTML="<option value=''>Default output</option>";ds.filter(d=>d.kind==='audioinput').forEach(d=>{let o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||'Microphone';mi.appendChild(o)});ds.filter(d=>d.kind==='audiooutput').forEach(d=>{let o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||'Output';ou.appendChild(o)});status(`Found ${ds.filter(d=>d.kind==='audioinput').length} input(s) and ${ds.filter(d=>d.kind==='audiooutput').length} output(s).`)}catch(e){status('Device error: '+e.message)}}
async function output(){const id=$("out").value;if(!id)return;try{if($("audio").setSinkId)await $("audio").setSinkId(id);status('Output selected.')}catch(e){status('Output selection failed: '+e.message)}}
$("out").onchange=output;$("refresh").onclick=devices;
$("cableIn").onclick=async()=>{await devices();const o=[...$("out").options].find(x=>/cable input/i.test(x.textContent));if(o){o.selected=true;await output()}else status('VB-CABLE CABLE Input was not found by Chrome.')};
$("cableOut").onclick=async()=>{await devices();const o=[...$("mic").options].find(x=>/cable output/i.test(x.textContent));if(o){o.selected=true;status('VB-CABLE CABLE Output selected as microphone.')}else status('VB-CABLE CABLE Output was not found by Chrome.')};
async function initTTS(){if(tts)return;status('Loading browser voice-cloning engine… first load is large and cached by Chrome.');const engine=new ChatterboxEngine({onProgress:p=>{if(p?.status)status('Voice model: '+p.status+(p.progress!=null?' '+Math.round(p.progress*100)+'%':'')}});tts=await VoxShot.create({engine,minChunkLength:20,device:'auto'});status('Voice-cloning engine ready.');}
async function clone(){const f=$("wav").files[0];if(!f)throw Error('Choose a WAV first.');await initTTS();status('Encoding your WAV voice…');await tts.cloneVoice(f);voiceReady=true;$("wavName").textContent='Cloned: '+f.name;status('Custom WAV voice is ready.');}
$("wav").onchange=()=>{const f=$("wav").files[0];if(f)$("wavName").textContent=f.name};$("loadVoice").onclick=async()=>{try{await clone()}catch(e){status('Clone failed: '+(e.stack||e.message))}};
async function speak(text){if(!voiceReady||busy||!running)return;busy=true;ignoreUntil=performance.now()+1000;try{status('Speaking: '+text);const speech=tts.play(text,{speed:1,volume:1});await speech.done;status('Listening…')}catch(e){status('TTS failed: '+e.message)}finally{busy=false;ignoreUntil=performance.now()+500}}
function setupRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)throw Error('Chrome Speech Recognition is unavailable. Use desktop Chrome.');recognition=new SR();recognition.continuous=true;recognition.interimResults=false;recognition.lang='en-US';recognition.onresult=e=>{if(!running||busy||performance.now()<ignoreUntil)return;for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal){const text=e.results[i][0].transcript.trim();if(!text||text===lastText&&performance.now()-lastAt<3000)continue;lastText=text;lastAt=performance.now();speak(text)}};recognition.onerror=e=>{if(running)status('STT: '+e.error)};recognition.onend=()=>{if(running&&!busy)try{recognition.start()}catch{}}}
async function meterStart(){const id=$("mic").value;micStream=await navigator.mediaDevices.getUserMedia({audio:id?{deviceId:{exact:id}}:{}});ctx=new AudioContext({latencyHint:'interactive'});await ctx.resume();analyser=ctx.createAnalyser();analyser.fftSize=256;ctx.createMediaStreamSource(micStream).connect(analyser);const a=new Uint8Array(analyser.fftSize);const tick=()=>{if(!running)return;analyser.getByteTimeDomainData(a);let s=0;for(const v of a){let x=(v-128)/128;s+=x*x}$("meter").style.width=Math.min(100,Math.sqrt(s/a.length)*650)+'%';raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick)}
function meterStop(){if(raf)cancelAnimationFrame(raf);raf=0;if(micStream)micStream.getTracks().forEach(t=>t.stop());micStream=null;if(ctx)ctx.close().catch(()=>{});ctx=null}
$("test").onclick=async()=>{try{if(!voiceReady)await clone();const was=running;running=true;await speak('This is a test of my custom WAV cloned voice.');running=was}catch(e){status('Test failed: '+e.message)}};
$("start").onclick=async()=>{try{if(!voiceReady)await clone();await devices();await meterStart();setupRecognition();running=true;recognition.start();$("start").disabled=true;$("stop").disabled=false;status('Listening… speak normally.')}catch(e){running=false;meterStop();status('START FAILED: '+(e.stack||e.message))}};
$("stop").onclick=()=>{running=false;busy=false;try{recognition?.stop()}catch{}meterStop();$("start").disabled=false;$("stop").disabled=true;status('Stopped.')};devices();