const $ = (id) => document.getElementById(id);
const status = $('status'), cloneStatus = $('cloneStatus'), voiceFile = $('voiceFile'), inputDevice = $('inputDevice'), outputDevice = $('outputDevice'), routingStatus = $('routingStatus'), text = $('text'), player = $('player'), transcript = $('transcript'), cloneBtn = $('clone'), startBtn = $('start'), testBtn = $('test');
let tts = null, loading = null, cloned = false, listening = false, recognition = null, outputId = 'default', speaking = false, queue = [];
function setStatus(m,k=''){status.textContent=m;status.className=`status ${k}`}
function fail(e){console.error(e);const m=e?.message||String(e);setStatus(m,'err');cloneStatus.textContent=m}
async function getTTS(){if(tts)return tts;if(loading)return loading;loading=(async()=>{setStatus('Loading VoxShot…');const mod=await import('https://esm.sh/gh/m96-chan/voxshot@main');if(!mod.VoxShot||!mod.ChatterboxEngine)throw Error('VoxShot/Chatterbox failed to load.');setStatus('Starting Chatterbox model…');const engine=new mod.ChatterboxEngine({stallTimeoutMs:300000,onProgress:p=>{if(p?.status)setStatus(`Chatterbox: ${p.status}${p.progress!=null?` ${Math.round(p.progress)}%`:''}`)}});tts=await mod.VoxShot.create({engine,device:'auto',minChunkLength:20});setStatus(`Chatterbox ready (${tts.device||'auto'}).`,'ok');return tts})().catch(e=>{tts=null;throw e}).finally(()=>loading=null);return loading}
async function cloneWav(){try{const f=voiceFile.files?.[0];if(!f)throw Error('Choose your WAV file first.');if(!/\.wav$/i.test(f.name)&&!/^audio\/(wav|x-wav|wave)$/i.test(f.type))throw Error('Please choose a WAV file.');if(f.size<10000)throw Error('Use a clean 5–15 second WAV recording.');cloned=false;cloneBtn.disabled=true;cloneStatus.textContent='Loading the voice-cloning model…';const engine=await getTTS();cloneStatus.textContent='Cloning your WAV voice…';setStatus('Cloning your WAV voice…');await engine.cloneVoice(f);cloned=true;cloneStatus.textContent=`Voice ready: ${f.name}`;setStatus('Voice clone ready!','ok')}catch(e){cloned=false;fail(e)}finally{cloneBtn.disabled=false}}
async function speak(v){if(!cloned)return;v=v.trim().slice(0,120);if(!v)return;const engine=await getTTS();speaking=true;try{setStatus('Speaking cloned voice…');const a=await engine.speak(v);if(outputId!=='default'&&player.setSinkId)await player.setSinkId(outputId);await a.play()}finally{speaking=false}}
async function drain(){if(speaking)return;while(queue.length&&listening){try{await speak(queue.shift())}catch(e){fail(e)}}if(listening)setStatus('Listening — speak naturally.','ok')}
function recognitionSetup(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return null;const r=new SR();r.lang='en-US';r.continuous=true;r.interimResults=true;r.onstart=()=>setStatus('Listening — speak naturally.','ok');r.onresult=e=>{let f='',i='';for(let n=e.resultIndex;n<e.results.length;n++){const s=e.results[n][0]?.transcript||'';e.results[n].isFinal?f+=s:i+=s}if(f.trim()){transcript.textContent=f.trim();if(queue.length>=2)queue.shift();queue.push(f);void drain()}else if(i.trim())transcript.textContent=i.trim()};r.onerror=e=>{if(e.error==='not-allowed'||e.error==='service-not-allowed'){listening=false;setStatus('Chrome blocked microphone/speech recognition permission.','err')}else if(e.error!=='aborted'&&e.error!=='no-speech')setStatus(`Speech recognition: ${e.error}`,'err')};r.onend=()=>{if(listening)setTimeout(()=>{try{r.start()}catch{}},250)};return r}
function startEcho(){try{if(!cloned)throw Error('Clone the WAV voice first.');recognition ||= recognitionSetup();if(!recognition)throw Error('Use current Chrome or Edge for browser speech recognition.');listening=true;queue=[];transcript.textContent='Listening…';startBtn.textContent='Echo is running…';try{recognition.start()}catch{}}catch(e){fail(e)}}
function stopEcho(){listening=false;queue=[];try{recognition?.abort()}catch{}startBtn.textContent='Start voice echo';setStatus(cloned?'Voice clone ready.':'Ready.')}
async function testVoice(){try{if(!cloned)throw Error('Clone the WAV voice first.');if(!text.value.trim())throw Error('Type something to test first.');await speak(text.value);if(!listening)setStatus('Test complete.','ok')}catch(e){fail(e)}}
async function refreshDevices(){if(!navigator.mediaDevices?.enumerateDevices)return;const ds=await navigator.mediaDevices.enumerateDevices();inputDevice.innerHTML='<option value="">Default microphone</option>';outputDevice.innerHTML='<option value="default">Default Windows output</option>';for(const d of ds){if(d.kind==='audioinput')inputDevice.add(new Option(d.label||'Microphone',d.deviceId));if(d.kind==='audiooutput'){const l=/cable input|vb-audio cable|virtual audio cable/i.test(d.label||'')?'VB-CABLE — CABLE Input':(d.label||'Audio output');outputDevice.add(new Option(l,d.deviceId))}}if([...outputDevice.options].some(o=>o.value===outputId))outputDevice.value=outputId;routingStatus.textContent=`Voice output → ${outputDevice.selectedOptions[0]?.text||'Default Windows output'}.`}
voiceFile.addEventListener('change',()=>{const f=voiceFile.files?.[0];cloneStatus.textContent=f?`Selected: ${f.name}`:'No voice loaded.';setStatus(f?'WAV selected. Press Clone WAV voice.':'Ready.')});cloneBtn.addEventListener('click',cloneWav);$('clearVoice').addEventListener('click',()=>{stopEcho();cloned=false;voiceFile.value='';cloneStatus.textContent='No voice loaded.';setStatus('Voice clone cleared.')});startBtn.addEventListener('click',startEcho);$('stop').addEventListener('click',stopEcho);testBtn.addEventListener('click',testVoice);$('refreshDevices').addEventListener('click',()=>refreshDevices().catch(fail));outputDevice.addEventListener('change',()=>{outputId=outputDevice.value||'default';routingStatus.textContent=`Voice output → ${outputDevice.selectedOptions[0]?.text||'Default Windows output'}.`});window.addEventListener('error',e=>fail(e.error||Error(e.message)));window.addEventListener('unhandledrejection',e=>fail(e.reason||Error('Unhandled browser error')));refreshDevices().catch(()=>{});